name: flutter_aero_airways
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  
  dio_smart_retry: ^7.0.1
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.2.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.6.11
  firebase_core: ^3.4.0
  firebase_storage: ^12.3.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.4
  form_validator: ^2.1.1
  iconsax: ^0.0.8
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.12
  sign_button: ^2.0.6
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  intl: ^0.20.2
  flutter_spinkit: ^5.2.1
  pull_to_refresh: ^2.0.0
  permission_handler: ^12.0.1
  flutter_google_maps_webservices: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  mockito: ^5.4.0

  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path_android: "assets/icons/icon.png"
  android_adaptive_icon_background: "#07120E"
  android_adaptive_icon_foreground: "assets/icons/icon.png"
  adaptive_icon_background: "#07120E"
  # For iOS, we use a different image and background color
  ios: true
  image_path_ios: "assets/icons/icon.png"
  background_color_ios : "#07120E"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
