// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCV_XMx1XrNPS2J0S1EW5sIZg1uJ34j3jo',
//     appId: '1:43359388157:web:2da3f71031360e6578d994',
//     messagingSenderId: '43359388157',
//     projectId: 'flutter-aero-airways',
//     authDomain: 'flutter-aero-airways.firebaseapp.com',
//     storageBucket: 'flutter-aero-airways.firebasestorage.app',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDnhbHWqIyXe6oveAx1IUxHvEyj8w47rYM',
//     appId: '1:43359388157:android:81ea378a1a6359d278d994',
//     messagingSenderId: '43359388157',
//     projectId: 'flutter-aero-airways',
//     storageBucket: 'flutter-aero-airways.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDVvOTIeQK9tWpa6cRGLwnUQ3sXGuBzZZA',
//     appId: '1:43359388157:ios:365100f122e3b2de78d994',
//     messagingSenderId: '43359388157',
//     projectId: 'flutter-aero-airways',
//     storageBucket: 'flutter-aero-airways.firebasestorage.app',
//     iosBundleId: 'com.example.flutterAeroAirways',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyDVvOTIeQK9tWpa6cRGLwnUQ3sXGuBzZZA',
//     appId: '1:43359388157:ios:365100f122e3b2de78d994',
//     messagingSenderId: '43359388157',
//     projectId: 'flutter-aero-airways',
//     storageBucket: 'flutter-aero-airways.firebasestorage.app',
//     iosBundleId: 'com.example.flutterAeroAirways',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCV_XMx1XrNPS2J0S1EW5sIZg1uJ34j3jo',
//     appId: '1:43359388157:web:f453aea3a099b47778d994',
//     messagingSenderId: '43359388157',
//     projectId: 'flutter-aero-airways',
//     authDomain: 'flutter-aero-airways.firebaseapp.com',
//     storageBucket: 'flutter-aero-airways.firebasestorage.app',
//   );
// }
